### ISSUE TITLE
Why do you use CompileProgram?

### ISSUE THREAD

**Issue by DeafMan1983** [Rabbid76/PyGameExamplesAndAnswers#3]
Hello,

I am sorry I don't understand what does it mean for[ CompileProgram](https://github.com/Rabbid76/PyGameExamplesAndAnswers/blob/b7fb064fa72489929cd2abb53ae90f1af8aec595/examples/pygame_opengl/opengl_4/pygame_opengl_mesh_cube_texture_array.py#L105)?

Please use "normal" Modern OpenGL like
glCreateProgram, glAttachShader, glLinkProgram and glDetachShader

Sorry I don't like who has cheated function for Python. You know many coders miss understand what does it work for OpenGL under Python. Please make sure "legit" OpenGL 4

**Comment by Rabbid76** [comment]
See [`OpenGL.GL.shaders.compileProgram()`](http://pyopengl.sourceforge.net/documentation/pydoc/OpenGL.GL.shaders.html)

**Comment by DeafMan1983** [comment]
OK No problem... But I never use CompileProgram(). I use only Legal GL Functions. Thanks!

**Comment by Rabbid76** [comment]
The function can be replaced with

```py
sh_objs = []
for sh_code in [(GL_VERTEX_SHADER, glsl_vert), (GL_FRAGMENT_SHADEr, glsl_frag)]:
    sh_obj = glCreateShader(sh_code[0])
    glShaderSource(sh_obj, sh_code[1])
    glCompileShader(sh_obj)
    result = glGetShaderiv(sh_obj, GL_COMPILE_STATUS )
    if not result:
        print( glGetShaderInfoLog(sh_obj) )
    sh_objs.append(sh_obj)

program = glCreateProgram()
for shObj in sh_objs: glAttachShader(program, shObj)
glLinkProgram(program)
if not glGetProgramiv(program, GL_LINK_STATUS):
    print(glGetProgramInfoLog(program))
```
